first check
AlexsandrBrachii/java-shareit pull request #3
Opened 2023-06-15 18:03 UTC by AlexsandrBrachii

2023-06-16 14:18 UTC, TomattmanYandex requested changes
привет, хорошая работа, коменты в коде,
проверь на однотипные моменты там где не коментировал
также надо было сделать тест json маппера, лучше бы придумать хотя бы один вариант такого теста

2023-06-16 14:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllBookings(long userId, String stateS, int from, int size) {
не лучше имя для переменной stateS

попробуй в контроллере в реквест параметрах сразу получать не строку а енам

2023-06-16 14:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        State state = checkState(stateS);
почему checkState а не getState или transformState

2023-06-16 14:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        PageRequest pageRequest = getPageRequest(from, size);
В параметрах кажется приходит не номер страницы а с какого элемента начиная а pageRequest принимает номер страницы

2023-06-16 14:18 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        userIsNull(userId);
зачем эта проверка если параметр обязательный?

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +public class BookingIntegrationTest {
Надо использовать имя класса который тестируем
BookingServiceIntegrationTest

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +        BookingDto created = bookingService.createBooking(userId, newBooking);
А что если сервис не создал ничего в базе, а просто вернул новую Dto тест тогда не упадет
в интеграционных тестах лучше проверять делая запрос в базу
т.е. создали через сервис, для проверки получили из репозитория

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    User owner;
зачем эти все переменные?

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    User owner;
Ладно понял зачем, но все же зачем они, лучше в каждом тесте сделать запрос в базу и сравнить, в зависимости от настроек, база может быть одна на все тесты, и в одном тесте ты можешь что то удалить и тогда эти переменные уже будет не нужны
лучше вместо того чтобы хранить переменные в памяти, просто делать запрос в базу, чтобы проверить что то что в базе соответсвует тому, что вернул сервис

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +    private final EntityManager em;
не проще ли использовать репозитории

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
тесты которые задействуют базу данных должны запускаться не на основной базе данных

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +@DataJpaTest
тесты должны запускаться не на основной бд

2023-06-16 14:18 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private User user;
снова кучи каких то переменных

2023-06-22 12:03 UTC, AlexsandrBrachii commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllBookings(long userId, String stateS, int from, int size) {
Я попробовал в контроллере сделать так что бы он сразу enum получал, но столкнулся с такой проблемой что тесты в postman перестали проходить, потому что им там определённый ответ нужен, а из-за того что Spring не понимает как не известный State обработать,  он сам выбрасывает своё исключение, и у меня его даже никак перехватить не получается. Решил пока что String оставить

2023-06-22 16:11 UTC, AlexsandrBrachii commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private User user;
Разреши пожалуйста я их оставлю, мне просто так легче для восприятия

2023-06-23 10:54 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllBookings(long userId, String stateS, int from, int size) {
Окок, значит все так и должно быть

2023-06-23 10:58 UTC, TomattmanYandex approved these changes
Принято

2023-06-24 09:18 UTC, merged